site_name: Mes cours

# Repository
repo_name: Edition
repo_url: https://github.com/louisonsarlinmagnus/cours-isen

nav:
  - Accueil: index.md
  - Tech:
    - Cyber Sécurité: tech-cybersecurite.md
    - Developpement Opérationnel: tech-DevOps.md
    - Intelligence Artificielle: tech-ia.md
    - Linux Embarqué: tech-linuxEmbarque.md
    - Opto-électronique: tech-optoElectronique.md
    - Réseaux électriques: tech-reseauxElectriques.md
    - Réseaux informatiques: tech-reseau.md
    - Smart-Card: tech-smartCard.md
    - Système d'exploitation: tech-OS.md
  - Sciences molles:
    - Gestion de la qualité: molle-qualite.md
    - Stratégie internationale: molle-strategieInternationale.md
  - Recherches:
    - Les réseaux électriques: recherche-reseauxElec.md
    - Transition énergétique: recherche-transitionEnergetique.md
  - CheatSheet: mdCheat.md
  - A propos: about.md


theme: 
  name: material
  highlightjs: true

markdown_extensions:
  - codehilite:
      linenums: true
  - admonition
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML


copyright: '&copy; 2020 Louison SARLIN--MAGNUS'