site_name: Mes cours

# Repository
repo_name: Edition
repo_url: https://github.com/louisonsarlinmagnus/cours-isen

nav:
  - Accueil: index.md
  - Tech:
    - Cyber Sécurité: tech/cybersecurite.md
    - Developpement Opérationnel: tech/devOps.md
    - Intelligence Artificielle: tech/ia.md
    - Linux Embarqué: tech/linuxEmbarque.md
    - Opto-électronique: tech/optoElectronique.md
    - Réseaux électriques: tech/reseauxElectriques.md
    - Réseaux informatiques: tech/reseau.md
    - Smart-Card: tech/smartCard.md
    - Système d'exploitation: tech/os.md
  - Sciences molles:
    - Droit du numérique: molle/droitNum.md
    - Gestion de la qualité: molle/qualite.md
    - Stratégie internationale: molle/strategieInternationale.md
  - Recherches:
    - Les réseaux électriques: rech/reseauxElec.md
    - Transition énergétique: rech/transitionEnergetique.md
  - CheatSheet: 
    - Résumé: cheat/resume.md
    - Titres: cheat/titres.md
    - Listes: cheat/listes.md
    - Liens: cheat/liens.md
    - Images: cheat/images.md
    - Code: cheat/code.md
    - LaTex: cheat/latex.md
    - Tableaux: cheat/tableaux.md
    - Diagrammes: cheat/diagrammes.md
    - Tabs: cheat/tabs.md
    - SuperFences: cheat/superfences.md
    - Citation: cheat/citation.md
    - Règles: cheat/regles.md
    - Smileys: cheat/smileys.md
    - Vidéos: cheat/videos.md
    - Blocs d'alerte: cheat/blocs.md
    - CheatSheet: cheatSheet.md
  - A propos: about.md


theme: 
  name: material
  highlightjs: true

markdown_extensions:
  - codehilite:
      linenums: true
  - admonition
  - attr_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - footnotes

extra_css:
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.css

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js

copyright: '&copy; 2020 Louison SARLIN--MAGNUS'