name: Mise a jour de la doc
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Job de mise a jour
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1

      - name: Install theme
        run: pip install mkdocs-gitbook

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}